language: python
python: 3.5
env:
- TOXENV=py27
- TOXENV=py34
- TOXENV=py35
install:
- pip install -U tox
script:
- tox
notifications:
  slack: crim-ca:A7jqt2VJWnPwN6A3AZXJ40gt
deploy:
  provider: pypi
  distributions: bdist_wheel
  user: crim-ca
  password:
    secure: iVmAqp2rLMd7yaWMismfecm5oz9WQ4G2xqB+DDOkY5wgxU/tmaeWrp2SwZhf5f8gWDX9hFoRekctkq6bANfSY5zCjmkzxJSHg7Uzt8x0vOCXenQo1+EujFJRnfSp9Hyl47jQaWU0/2N4F4I/lXxeojKhwGgyuaiyiQtqthfrH7UF+BFjltIctcLODolk/O0SJQMImnMkt8L7PR2Jcfkr8gaa+yw6AIuNN5QOQR9yksOByAsFziQoMg4UVenKGyamiEYzNbVNUsiWA7h+Ivc7KhC3dvKgpwS/eo/tX4JbxfN/fF9R5hJBT7yZRA/dSztaCxV6M3+0dnpj9GHWVRdDH6CgUzAzUrpVxLbKfHLOyN+wC3uwWsqCrlUkE+a7m8kb6wGjWc7Z47AQiYvrnNvwGGYc+Vm+Atcgc1EWmYvYkeLyTVibWIFP/PZInETEyj7l0fB7cbZ+QMyMk8vekrd5IBhvrF/GaEV9m1jONa54ubbQB+oMolk8uM6taVx4qGZgeKLpWa+hMo/jWz/TG9Ka4vG7C4cgC/y1DJX1G2jZVazKBjbJiBFm2HDFnWLcBN36Y3w/zdb6wqk9wmwCpX+7t0/aAhDWpi64hWtLMstaE9n6XJUvq/SpfJxzeR+Po1ylmzlFsriBRKaLEhxyjB2Efn9Lpuyu8SBLsH9331H6As0=
  on:
    tags: true
