language: python

python: 3.5
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35

install:
  - pip install -U tox

script:
  - tox

notifications:
  slack: crim-ca:A7jqt2VJWnPwN6A3AZXJ40gt

# deploy:
#   provider: pypi
#   distributions: sdist
#   user: crim-ca
#   password:
#     secure: PLEASE_REPLACE_ME
#   on:
#     tags: true
#     repo: audreyr/python_boilerplate
#     condition: $TOXENV == py27
